### ISSUE TITLE
Off Canvas Side nav is cutoff?

### ISSUE THREAD

**Issue by Orbyt** [ewall/meteor-foundation#12]
Pic for reference:

![](http://i.imgur.com/WBnSliP.png)

Basically the offcanvas menu is completely cuttoff. Ideas?

EDIT: Ok, it looks like it cuts off at how much content you have? Is this default behavior? screenie: http://prntscr.com/77ztgr

**Comment by ewall** [comment]
Hi, @Orbyt -- Nothing I know of off hand, sadly. Are you able to reproduce it if you use the straight Foundation CSS & JS instead of the Meteor package?

This is more likely an issue with Foundation itself (or the particulars of your implementation) than something in this Meteor package. Might be a good idea to check the [Foundation Forum](http://foundation.zurb.com/forum) and [Foundation's GitHub Issues](https://github.com/zurb/foundation/issues) -- in the past I've found solutions there pretty quickly.

Either way, I'd be interested to know how it turns out!

**Comment by nanderson94** [comment]
```css
.off-canvas-wrap, .inner-wrap {
	min-height: 100vh;
}
```
I used this on my personal site to fix that issue.

**Comment by ewall** [comment]
@Orbyt -- any updates? I don't think this is a problem with my Meteor package per se but more of a Foundation thing, so I'd like to close out this issue... Thanks!

**Comment by Orbyt** [comment]
@ewall I dont remember if I solved it or not, but if your package just wraps Foundation its more than likely an issue with either Foundation or my implementation.

**Comment by ewall** [comment]
Water under the bridge then, or something like that.
