### ISSUE TITLE
Foundation 6 support

### ISSUE THREAD

**Issue by yanickrochon** [ewall/meteor-foundation#19]
Foundation 6 was released 6 months ago, will that be updated, here?

And, is this project dead?

**Comment by ewall** [comment]
Since Foundation for Sites v6 was released, Zurb has maintained their own Meteor package which can be found here: **[https://atmospherejs.com/zurb/foundation-sites](https://atmospherejs.com/zurb/foundation-sites)**

So this package will be updated if there are further updates or tweaks to Foundation v5, but definitely no plans to jump to v6.

At some point I should probably update the README page to point people to Zurb's v6 package if they need it, eh? :)

**Comment by yanickrochon** [comment]
Thank you for the explanations. I'll take a look at that repo, then. Cheers!
